import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Footer from "@/components/Footer";

const raleway = Raleway({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-50 ${raleway.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
